[project]
name = "mcp-assignment-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tejalp68", email = "tejalpagar368@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]<2",
    "tiktoken>=0.14.0",
]

[project.scripts]
mcp-assignment-2 = "mcp_assignment_2:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
